const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');

const srcDir = path.join(__dirname, '..', 'static');
const distDir = path.join(__dirname, '..', 'dist');
const distStaticDir = path.join(distDir, 'static');
const compiledDict = path.join(distDir, 'lib', 'i18n-strings.js');

function copyDir(src, dest) {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }

  const entries = fs.readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
      console.log(`✅ Copied: static/${path.relative(srcDir, srcPath)}`);
    }
  }
}

/**
 * 生成 i18n-dict.js（window.I18N_DICT = { zh, en }）
 * 由编译后的 src/lib/i18n-strings.ts 提取，作为浏览器经典脚本消费的单一真相源。
 * 写入 source/static/js，使 dev（tsx 直接服务 source/static）与生产（copy 进 dist/static）均可用。
 */
async function generateI18nDict() {
  if (!fs.existsSync(compiledDict)) {
    console.warn('⚠️ 未找到编译产物 dist/lib/i18n-strings.js，跳过 i18n-dict.js 生成（请先 tsc 构建）');
    return;
  }
  const mod = await import(pathToFileURL(compiledDict).href);
  const zh = mod.zh || {};
  const en = mod.en || {};
  const out = `window.I18N_DICT = ${JSON.stringify({ zh, en })};\n`;
  const outPath = path.join(srcDir, 'js', 'i18n-dict.js');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out, 'utf-8');
  console.log('✅ Generated: static/js/i18n-dict.js');
}

/**
 * 生成 lang-detect.js（window.LangDetect.detectDefaultLang）
 * 由编译后的 src/lib/lang.ts 提取 resolveDefaultLanguage 源码（.toString()），
 * 注入 navigator.language + Intl 时区后包成浏览器全局。与 Node 端规则字面一致、零漂移。
 * 写入 source/static/js，dev（tsx 直接服务 source/static）与生产（copy 进 dist/static）均可用。
 */
async function generateLangRuntime() {
  const compiledLang = path.join(distDir, 'lib', 'lang.js');
  if (!fs.existsSync(compiledLang)) {
    console.warn('⚠️ 未找到编译产物 dist/lib/lang.js，跳过 lang-detect.js 生成（请先 tsc 构建）');
    return;
  }
  let mod;
  try {
    mod = await import(pathToFileURL(compiledLang).href);
  } catch (e) {
    console.warn('⚠️ 导入 dist/lib/lang.js 失败，跳过 lang-detect.js 生成:', e && e.message);
    return;
  }
  const fnSrc = (mod.resolveDefaultLanguage || '').toString();
  if (!fnSrc) {
    console.warn('⚠️ lang.js 未导出 resolveDefaultLanguage，跳过 lang-detect.js 生成');
    return;
  }
  const out =
    `// AUTO-GENERATED by scripts/copy-static.cjs — do not edit by hand.\n` +
    `// 浏览器默认语言探测（首装无 coordclaw.json 时）。权威语言 = coordclaw.json（安装页写入）。\n` +
    `// 规则与 Node 端 src/lib/lang.ts 同源（resolveDefaultLanguage 经 .toString() 注入），零漂移。\n` +
    `window.LangDetect = (function () {\n` +
    `  ${fnSrc}\n` +
    `  return {\n` +
    `    detectDefaultLang: function () {\n` +
    `      var tz = Intl.DateTimeFormat().resolvedOptions().timeZone || '';\n` +
    `      var loc = (navigator.language || navigator.userLanguage || '');\n` +
    `      return resolveDefaultLanguage({ timeZone: tz, localeHint: loc });\n` +
    `    }\n` +
    `  };\n` +
    `})();\n`;
  const outPath = path.join(srcDir, 'js', 'lang-detect.js');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out, 'utf-8');
  console.log('✅ Generated: static/js/lang-detect.js');
}

(async () => {
  try {
    await generateI18nDict();
    await generateLangRuntime();
    copyDir(srcDir, distStaticDir);
    console.log('✅ Static files copied to dist/static');
  } catch (error) {
    console.error('❌ Error copying static files:', error.message);
    process.exit(1);
  }
})();
